### ISSUE TITLE
Reusing streams and observing them causes only the output of the last stream to show

### ISSUE THREAD

**Issue by alfabetacain** [alfert/reaxive#13]
The following ExUnit test should results in two different messages being sent to the current process. 

```
  test "does not work" do
    me = self
    {:ok, rx} = Rx.Impl.start()
    rx1 = Rx.map(rx, fn _ -> "stream1" end)
    Observable.subscribe(rx1, fn (tag, value) -> send me, {tag, value} end)
    rx2 = Rx.map(rx, fn _ -> "stream2" end)
    Observable.subscribe(rx2, fn (tag, value) -> send me, {tag, value} end)
    Rx.Impl.on_next(rx, "input value")
    receive do
      input1 -> 
        IO.puts "first input: #{inspect input1}"
        receive do
          input2 ->
            IO.puts "second input: #{inspect input2}"
        end
    end
  end
```

One message should contain `"stream1"` and the other `"stream2"`.
However, I get the output:

```
first input: {:on_next, "stream2"}
second input: {:on_next, "stream2"}
```

It seems that only the output from the second stream (`rx2` is used). I do however receive two messages. 

Is this behavior intentional or the result of a bug?

**Comment by alfert** [comment]
This works as expected, but we can discuss, whether this is a useful situation or not. This could be a different behavior from Reactive Extensions or their Scala/JS relatives, because we use here proper processes and do not have objects encapsulating functions. 

`Rx` creates a (single) process and you get its pid as a result of `Rx.Impl.start()`. Applying the `Rx.map` adds a synchronous map-functionality to this process (similar to `Enum` or `Stream`). Doing it the second time, does the same, taking the result of the first map and applying the second map function. In both cases, your subscriptions subscribe to the same `Rx` process, therefore the value send to `me` is the value after applying both map-functions. 

The idiomatic version of your example is the following: 

```Elixir
    me = self
    {:ok, rx}  = Rx.Impl.start()
    rx1 = rx |> Rx.map(fn _ -> "stream1" end) |> Rx.map(fn _ -> "stream2" end)
    Observable.subscribe(rx1, fn (tag, value) -> send me, {tag, value} end)
    Observable.subscribe(rx1, fn (tag, value) -> send me, {tag, value} end)
    Rx.Impl.on_next(rx, "input value")
     receive do
       input1 -> 
         IO.puts "first input: #{inspect input1}"
         receive do
           input2 ->
             IO.puts "second input: #{inspect input2}"
         end
     end
```
  
What you require is an asynchronous stream composition. This can be achieved with the `Rx.async` function.  

```Elixir
    me = self
    {:ok, rx} = Rx.Impl.start()
    rx1 = rx  |> Rx.map(fn _ -> "stream1" end)  |> Rx.async()  |> Rx.map(fn _ -> "stream2" end)
    Observable.subscribe(rx, fn (tag, value) -> send me, {tag, value} end)
    Observable.subscribe(rx1, fn (tag, value) -> send me, {tag, value} end)
    Rx.Impl.on_next(rx, "input value")
     receive do
       input1 -> 
         IO.puts "first input: #{inspect input1}"
         receive do
           input2 ->
             IO.puts "second input: #{inspect input2}"
         end
     end
```

Now you get different results. A little test in `IEx` gives me: 

```
first input: {:on_next, "stream1"}
second input: {:on_completed, #PID<0.139.0>}
```

To get all results, we need four receives: two for `:on_next` and two for `:on_completed`. Due to the nondeterminism you cannot guarantee that the `:on_next` messages appear before `:completed`. Changing your observers helps here by ignoring any message unless it is `:on_next`: 

```Elixir
    alias Reaxive.Rx
    me = self
    sender_fun = fn (:on_next = tag, value) ->  send me, {tag, value}
                             (_, _value ) -> :ok end
    {:ok, rx} = Rx.Impl.start()
    rx1 = rx  |> Rx.map(fn _ -> "stream1" end)  |> Rx.async()  |> Rx.map(fn _ -> "stream2" end)
    Observable.subscribe(rx, sender_fun)
    Observable.subscribe(rx1,sender_fun)
    Rx.Impl.on_next(rx, "input value")
     receive do
       input1 -> 
         IO.puts "first input: #{inspect input1}"
         receive do
           input2 ->
             IO.puts "second input: #{inspect input2}"
         end
     end
```

Pasting this into a fresh `IEx` shell in the reaxive environment, gives you the expected result: 
```Elixir
first input: {:on_next, "stream1"}
second input: {:on_next, "stream2"}
:ok
iex(10)>
```

This is a much more useful example for the `Rx.async` than my example in the API docs. I should change the API docs to this or a similar example. Please feel free to send a PR!

**Comment by alfabetacain** [comment]
Thanks a lot for the detailed answer and examples. 

What I was searching for was a way to split the output of a stream. 
In the last example you provided, both mappings are performed on the same stream and form a single new stream. 

Is it possible to split a stream, so that each mapping function would work only on the original output?

In my example, I expected to have a single node capable of emitting events (let's call it A). 
I wanted to have two different streams working on this output (let's call them B and C). 
I expected that, when emitting values on A, both B and C would receive values like this:
A -> B
A -> C

Instead what I encountered were this: 
A -> B -> C
which is also what is happening in your example, as far as I understand.

Is it possible to achieve this kind of behavior?

**Comment by alfert** [comment]
This is easy: Just have two observers or async combinators on the source stream: 

```Elixir
    alias Reaxive.Rx
    me = self
    sender_fun = fn (:on_next = tag, value) ->  send me, {tag, value}
                             (_, _value ) -> :ok end
    {:ok, rx} = Rx.Impl.start()
    rx1 = rx  |> Rx.async() |> Rx.map(fn _ -> "stream1" end) 
    rx2 = rx |> Rx.async()  |> Rx.map(fn _ -> "stream2" end)
    Observable.subscribe(rx2, sender_fun)
    Observable.subscribe(rx1, sender_fun)
    Rx.Impl.on_next(rx, "input value")
     receive do
       input1 -> 
         IO.puts "first input: #{inspect input1}"
         receive do
           input2 ->
             IO.puts "second input: #{inspect input2}"
         end
     end
```
This results in: 

```Elixir
first input: {:on_next, "stream2"}
second input: {:on_next, "stream1"}
:ok
iex(11)> 
```
